#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"

# List of dotfile targets from install.conf.yaml
declare -a targets=(
    "$HOME/.bash"
    "$HOME/.bashrc"
    "$HOME/.gitconfig"
    "$HOME/.gitignore_global"
    "$HOME/.tmux.conf"
    "$HOME/.shell"
    "$HOME/.vim"
    "$HOME/.vimrc"
)

# Backup existing targets that are not symlinks
for target in "${targets[@]}"; do
    if [ -e "$target" ] && [ ! -L "$target" ]; then
        mv "$target" "${target}.bak"
        echo "Existing $target found and moved to ${target}.bak"
    fi
done

git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
